#!/bin/bash

set -o vi
bind -m vi-command 'Control-l: clear-screen'
bind -m vi-insert 'Control-l: clear-screen'

export HISTCONTROL=ignoredups:erasedups # no duplicate entries
PS1='[\u@\h \W]\$ '

shopt -s autocd  # change to named directory
shopt -s cdspell # autocorrects cd misspellings
shopt -s cmdhist # save multi-line commands in history as single line
shopt -s dotglob
shopt -s histappend     # do not overwrite history
shopt -s expand_aliases # expand aliases
shopt -s checkwinsize   # checks term size when bash regains control

[ -f ~/.config/aliases ] && source ~/.config/aliases
