#!/bin/zsh
##
## alias
# quick comands
alias cls='clear'
alias e='exit' ; alias q='exit'
alias l='exa -l -a  --color=auto --git '
alias shutr='shutdown -r now'
alias shut='shutdown now'
alias py='python3'
alias doom='~/.emacs.d/bin/doom'
alias ap="sudo aptitude"
alias bat='batcat'
## git quick commands (because im lazy)
alias gits='git status'
alias gitls='exa -l -a --color=auto --git --git-ignore'
alias gitp='git push'
alias gitl='git log'
# moving files out of my home directory
alias bash='bash --rcfile ~/.config/bash/.bashrc'
#a little bit of fun
alias rr='curl -L https://raw.githubusercontent.com/keroserene/rickrollrc/master/roll.sh | bash'
alias par='curl parrot.live'
alias clock='tty-clock -Scxs'
alias weather='read weath ; curl wttr.in/$weath '
alias h='htop'
alias umat='unimatrix -a -f -l egGoncCskp'

alias -g ...='../..'
alias -g ....='../../..'
alias -g .....='../../../..'
alias -g ......='../../../../..'
