#+TITLE: Me Dot files
#+options: toc:nil
#+HTML: <div align=center> <br> <a href="https://github.com/hlissner/doom-emacs"><img src="https://img.shields.io/badge/Made_with-Doom_Emacs-blueviolet.svg?style=flat-square&amp;logo=GNU%20Emacs&amp;logoColor=white" alt="Made with Doom Emacs"></a></div>
* I used to be a productive person like you.. until I took dotfiles to the knee
Welcome to my dotfiles! I have spent countless hours writing, stressing and
redeploying them so I should know them like the back of my hand. That being said
I am me and I am stupid. Hence why I am on my 3rd rewrite of them (all hail
nix!) anyway there is a config for (split into its modules)

There is nothing special here. this is a generic home manager configuration. It
may be a good reasource for people who want to make a good home manager config

- chat
  installs
  + discord canary
  + element
- cli
  installs
  + a bunch of stuff [[file:modules/cli.nix][(check it out!)]]
  configures
  + TODO lf
  + neofetch
  + pulsemixer
  + topgrade
- emacs
  installs
  + emacs (pgtk-nativecomp)
  configures
  + (doom) :: you will need to symlink this
- email
  installs and configures
  + mbsync (isync) FIXME
  + msmtp
- fun
  just a bunch of jokes at this point
- git
  Pretty much just deals with git and the github cli
- neovim
  installs
  + neovim nightly
    configures
  + neovim :: you will need to symlink this yourself
- shell
  + zsh (with zplug for plugins)
    a hybrid between home manager and shell :)
- terminal
  + alacritty
  + tmux
    its another hybrid
- misc
  + castor
  # + libinput gestures

there are also a bunch of scripts I have and some other stuff I probably have
forgot about. Most config things are in ~config~ (duh)

* TODO
I need to do some stuff
- fix gtk apps
* Installations
You need to install [[https://nixos.org/guides/install-nix.html][nix]]
#+begin_src shell
curl -L https://nixos.org/nix/install | sh
#+end_src

[[https://github.com/nix-community/home-manager#installation][home manager]]
#+begin_src shell
nix-channel --add https://github.com/nix-community/home-manager/archive/master.tar.gz home-manager
nix-channel --update
nix-shell '<home-manager>' -A install
#+end_src

[[https://app.cachix.org/cache/nix-community][cachix (for emacs pgkt gcc)]]
#+begin_src shell
nix-env -iA cachix -f https://cachix.org/api/v1/install
cachix use nix-community
#+end_src

[[https://github.com/guibou/nixGL][nixGL (for alacritty)]]
#+begin_src shell
nix-channel --add https://github.com/guibou/nixGL/archive/master.tar.gz nixgl && nix-channel --update
nix-env -iA nixgl.nixGLDefault
#+end_src

then install my dotfiles
#+begin_src shell
git clone https://github.com/jeetelongname/dotfiles ~/.config/nixpkgs
home-manager switch
#+end_src
This may take a minute

** Any Questions email me here!
[[mailto:jeetelongname@gmail.com][jeetelongname@gmail.com]]
