#!/usr/bin/env bash
#                     __      
#    __  _____  ___  / /______
#   / / / / _ \/ _ \/ __/ ___/
#  / /_/ /  __/  __/ /_(__  ) 
#  \__, /\___/\___/\__/____/  
# /____/                      
#                     _____      
#   _________  ____  / __(_)___ _
#  / ___/ __ \/ __ \/ /_/ / __ `/
# / /__/ /_/ / / / / __/ / /_/ / 
# \___/\____/_/ /_/_/ /_/\__, /  
#                       /____/   
#                       for herbstluftwm
                      
# remeber to make this file runable!

hc() { # this aliases herbstclient to hc to make the conf more readable (don'ask me wat the $@ does)
    herbstclient "$@"
}

hc emit_hook reload

# remove all existing keybindings
hc keyunbind --all 

source ~/.config/herbstluftwm/keybinds
source ~/.config/herbstluftwm/programs

# theme
hc attr theme.tiling.reset 1
hc attr theme.floating.reset 1

# padding
hc pad 0 25 5 5 5
hc set window_gap 2
#hc set frame_gap 1

hc attr theme.border_width 2
hc attr theme.floating.border_width 2
hc attr theme.floating.outer_width 2

hc set frame_padding 1
hc set smart_window_surroundings 0
hc set smart_frame_surroundings 0
hc set mouse_recenter_gap 0

hc set frame_border_width 0
hc set always_show_frame 0
hc set frame_bg_transparent 1
hc set frame_transparent_width 0
hc set frame_gap 1

bg1="#242424"
bg2="#70cbe0"
hc attr theme.active.color "$bg2"
hc attr theme.normal.color "$bg1"
hc attr theme.urgent.color orange
hc attr theme.floating.outer_color "$bg1"
hc attr theme.active.inner_color "$bg2"
hc attr theme.active.outer_color "$bg2"
hc attr theme.background_color "#333333"
# hc set window_gap 5

# tags
tag_names=("dev" "www" "sys" "doc" "box" "chat" "mus" "vid" "gfx") 
# tag_names=( {1..9} ) # this is a list of numbers 1 to 9 (thats what the .. means)
tag_keys=( {1..9} 0 )

hc rename default "${tag_names[0]}" || true
for i in ${!tag_names[@]} ; do # this iterates through the tag list and adds a keybinding for them (this save typing out "hc keybind $Mod-1 use_index 1" 8 more times) 
    hc add "${tag_names[$i]}"
    key="${tag_keys[$i]}"
    if ! [ -z "$key" ] ; then
        hc keybind "$Mod-$key" use_index "$i"
        hc keybind "$Mod-Shift-$key" move_index "$i"
    fi
done
# rules
hc unrule -F
# hc rule class=XTerm tag=3 # move all xterms to tag 3
hc rule focus=on # normally focus new clients
#hc rule focus=off # normally do not focus new clients
# give focus to most common terminals
#hc rule class~'(.*[Rr]xvt.*|.*[Tt]erm|Konsole)' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' pseudotile=on
hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK|DESKTOP)' manage=off
hc set tree_style '╾│ ├└╼─┐' # i have no clue what this is but it reminds me of the windows pipe screensaver

# unlock, just to be sure
hc unlock

# do multi monitor setup here, e.g.:
# hc set_monitors 1280x1024+0+0 1280x1024+1280+0
# or simply:
# hc detect_monitors
