#!/bin/bash
## HLWM Xmobar Tag Status ######
# Version 0.1 by Scott Garrett #
# Wintervenom [(at)] gmail.com #
################################

hc () { #an alias
    herbstclient "$@"
}

tags () {
    # this is how the tags are formated. it uses printf and sed to form how the tags look
    # printf adds the space after every tag
    # hc tag_status is where the tag info is sourced
    # sed firsts removes the periods from the start of every tag (they are not useful)
    # then find the hashtag # and uses that to surround a set of characters seperated with white spaces with []
    # it then removes the hashtag
    # sending it all to stdout
    printf '%s ' $(hc tag_status | sed 's/\.//g;s/\(#\)\([[:print:]]*\)/[\2]/;s/\(:\)\([[:print:]]*\)/\1\2:/g')
    # printf '%s ' $(hc tag_status)
    echo
}

set -f
IFS=$'\t'
tags
hc -i tag_changed |
while read hook tag mon; do
    tags
done
