#                     __
#    __  _____  ___  / /______
#   / / / / _ \/ _ \/ __/ ___/
#  / /_/ /  __/  __/ /_(__  )
#  \__, /\___/\___/\__/____/
# /____/
#                     _____
#   _________  ____  / __(_)___ _
#  / ___/ __ \/ __ \/ /_/ / __ `/
# / /__/ /_/ / / / / __/ / /_/ /
# \___/\____/_/ /_/_/ /_/\__, /
#                       /____/
#                       for alacritty :)
env:
  TERM: screen-256color
window:
  dimensions:
    columns: 0
    lines: 0

  position:
    x: 10
    y: 10

  padding:
    x: 0
    y: 0

  dynamic_padding: false

  # Window title
title: Alacritty

scrolling:
  history: 10000
  multiplier: 3

# Font configuration
font:
  normal:
    family: Iosevka
    style: Regular

  bold:
    family: Iosevka
    style: Bold

  italic:
    family: Iosevka
    style: Italic

  size: 12.0

  offset:
    x: 0
    y: 1

  glyph_offset:
    x: 2
    y: 0
# fonts end here

# Colors (Horizon Dark)
colors:
  # Primary colors
  primary:
    background: '0x1c1e26'
    foreground: '0xe0e0e0'

  # Normal colors
  normal:
    black: '0x16161c'
    red: '0xe95678'
    green: '0x29d398'
    yellow: '0xfab795'
    blue: '0x26bbd9'
    magenta: '0xee64ac'
    cyan: '0x59e1e3'
    white: '0xd5d8da'

  # Bright colors
  bright:
    black: '0x5b5858'
    red: '0xec6a88'
    green: '0x3fdaa4'
    yellow: '0xfbc3a7'
    blue: '0x3fc4de'
    magenta: '0xf075b5'
    cyan: '0x6be4e6'
    white: '0xd5d8da'

window:
  opacity: 1

# Allow terminal applications to change Alacritty's window title.
dynamic_title: true

cursor:
  style: Block
  unfocused_hollow: true
  vi_mode_style: Block

live_config_reload: true

debug:
  persistent_logging: false
  log_level: Warn

mouse:
  double_click: {threshold: 300}
  triple_click: {threshold: 300}

  hints::
    Default:
      - (Linux/BSD) xdg-open

key_bindings:
  - {key: V, mods: Control|Shift, action: Paste}
  - {key: C, mods: Control|Shift, action: Copy}
#   - { key: Insert,   mods: Shift,         action: PasteSelection   }
#   - { key: Key0,     mods: Control,       action: ResetFontSize    }
#   - { key: Equals,   mods: Control,       action: IncreaseFontSize }
#   - { key: Add,      mods: Control,       action: IncreaseFontSize }
#   - { key: Subtract, mods: Control,       action: DecreaseFontSize }
#   - { key: Minus,    mods: Control,       action: DecreaseFontSize }
