#                     __
#    __  _____  ___  / /______
#   / / / / _ \/ _ \/ __/ ___/
#  / /_/ /  __/  __/ /_(__  )
#  \__, /\___/\___/\__/____/
# /____/
#                     _____
#   _________  ____  / __(_)___ _
#  / ___/ __ \/ __ \/ /_/ / __ `/
# / /__/ /_/ / / / / __/ / /_/ /
# \___/\____/_/ /_/_/ /_/\__, /
#                       /____/
#                       for alacritty :)
env:
  TERM: screen-256color
window:
  dimensions:
    columns: 0
    lines: 0

  position:
    x: 10
    y: 10

  padding:
    x: 5
    y: 5

  dynamic_padding: false

  # Window title
title: Alacritty

scrolling:
  history: 10000
  multiplier: 3

# Font configuration
font:
  normal:
    family: Iosevka
    style: Regular

  bold:
    family: Iosevka
    style: Bold

  italic:
    family: Iosevka
    style: Italic

  size: 12.0

  offset:
    x: 0
    y: 1

  glyph_offset:
    x: 0
    y: 0
# fonts end here
colors:
  # Default Colors (pencil dark)
  primary:
    background: "#212121"
    foreground: "#f1f1f1"
  # Normal colors
  normal:
    black: "#212121"
    red: "#c30771"
    green: "#10a778"
    yellow: "#a89c14"
    blue: "#008ec4"
    magenta: "#523c79"
    cyan: "#20a5ba"
    white: "#e0e0e0"
  # Bright colors
  bright:
    black: "#212121"
    red: "#fb007a"
    green: "#5fd7af"
    yellow: "#f3e430"
    blue: "#20bbfc"
    magenta: "#6855de"
    cyan: "#4fb8cc"
    white: "#f1f1f1"

background_opacity: 0.97

# Allow terminal applications to change Alacritty's window title.
#dynamic_title: true

cursor:
  style: Block
  unfocused_hollow: true
  vi_mode_style: Block

live_config_reload: true

debug:
  persistent_logging: false
  log_level: Warn

mouse:
  double_click: {threshold: 300}
  triple_click: {threshold: 300}

  url:
    Default:
      - (Linux/BSD) xdg-open

key_bindings:
  - {key: V, mods: Control|Shift, action: Paste}
  - {key: C, mods: Control|Shift, action: Copy}
#   - { key: Insert,   mods: Shift,         action: PasteSelection   }
#   - { key: Key0,     mods: Control,       action: ResetFontSize    }
#   - { key: Equals,   mods: Control,       action: IncreaseFontSize }
#   - { key: Add,      mods: Control,       action: IncreaseFontSize }
#   - { key: Subtract, mods: Control,       action: DecreaseFontSize }
#   - { key: Minus,    mods: Control,       action: DecreaseFontSize }
